### ISSUE TITLE
Error: Instance of 'WebScraperException'- Plugin is not working for Web

### ISSUE THREAD

**Issue by robotvinay** [tusharojha/web_scraper#19]
I was able to scrap the data using this package for Android,iOS,Desktop

But while testing in Web, i am getting this error

package : web_scraper: ^0.0.8

Error: Instance of 'WebScraperException'
    at Object.throw_ [as throw] (http://localhost:64427/dart_sdk.js:4348:11)
    at web_scraper.WebScraper.new.loadWebPage (http://localhost:64427/packages/web_scraper/web_scraper.dart.lib.js:75:23)
    at loadWebPage.throw (<anonymous>)
    at http://localhost:64427/dart_sdk.js:37962:38
    at _RootZone.runBinary (http://localhost:64427/dart_sdk.js:37815:58)
    at _FutureListener.thenAwait.handleError (http://localhost:64427/dart_sdk.js:32783:48)
    at handleError (http://localhost:64427/dart_sdk.js:33335:51)
    at Function._propagateToListeners (http://localhost:64427/dart_sdk.js:33361:17)
    at _Future.new.[_completeError] (http://localhost:64427/dart_sdk.js:33207:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:64427/dart_sdk.js:33246:31)
    at Object._microtaskLoop (http://localhost:64427/dart_sdk.js:38071:13)
    at _startMicrotaskLoop (http://localhost:64427/dart_sdk.js:38077:13)
    at http://localhost:64427/dart_sdk.js:33574:9

**Comment by tusharojha** [comment]
Hi @robotvinay 
Are you sure this is not a CORS issue?
Also, send the error message of `WebScraperException` using errorMessage() function of the same.

**Comment by tusharojha** [comment]
Closing this issue because of no response in the last 15 days. Feel free to reopen the issue when you're back!
