### ISSUE TITLE
is there Flutter Web support?

### ISSUE THREAD

**Issue by manzajp** [tusharojha/web_scraper#60]
im sorry but im new to Github so i wouldn't know where to ask but is there Flutter Web support for this plugin? 
It would seem that it does from pub.dev but im creating a simple sample and it didnt work on web but works on android emulator.
Below are the errors:

Error: Instance of 'WebScraperException'
    at Object.throw_ [as throw] (http://localhost:63522/dart_sdk.js:5087:11)
    at web_scraper.WebScraper.new.loadFullURL (http://localhost:63522/packages/web_scraper/web_scraper.dart.lib.js:94:23)
    at loadFullURL.throw (<anonymous>)
    at http://localhost:63522/dart_sdk.js:38657:38
    at _RootZone.runBinary (http://localhost:63522/dart_sdk.js:38527:59)
    at _FutureListener.thenAwait.handleError (http://localhost:63522/dart_sdk.js:33736:33)
    at handleError (http://localhost:63522/dart_sdk.js:34293:51)
    at Function._propagateToListeners (http://localhost:63522/dart_sdk.js:34319:17)
    at _Future.new.[_completeError] (http://localhost:63522/dart_sdk.js:34169:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:63522/dart_sdk.js:34205:31)
    at Object._microtaskLoop (http://localhost:63522/dart_sdk.js:38790:13)
    at _startMicrotaskLoop (http://localhost:63522/dart_sdk.js:38796:13)
    at http://localhost:63522/dart_sdk.js:34531:9

**Comment by tusharojha** [comment]
Hi @manzajp,
It's been reported that the package is not working properly on Flutter Web (check #59). I am closing this issue to keep things sorted. So you can check for updates on that issue & let's have the conversation over there.

Thanks.
